###
GET http://localhost:8080/api/v1/todos
accept: application/json

###
DELETE http://localhost:8080/api/v1/todos/08fb259e-6953-4347-b28f-90010f4288e7
accept: application/json


###
POST http://localhost:8080/api/v1/todos
content-type: application/json
accept: application/json

{
  "title": "Give it a break part 4",
  "completed": true,
  "userId": "b094e30c-5db7-4f02-86f0-943c2d317f99"
}

###
PUT http://localhost:8080/api/v1/todos/d44c3082-37da-4956-ba5f-234fef80ba5c
content-type: application/json

{
  "id": "d44c3082-37da-4956-ba5f-234fef80ba5c",
  "title": "Give it a BREAK part 2",
  "completed": false,
  "userId": "b094e30c-5db7-4f02-86f0-943c2d317f99"
}
